### ISSUE TITLE
[3.0 - NPMified] Default area bundles require simple-crafting module, not included in npm run init script

### ISSUE THREAD

**Issue by ghost** [RanvierMUD/bundle-example-areas#2]
**Describe the bug**
Default bundles appear to require simple-crafting mod which is not part of npm run init script. Resolvable manually by adding the simple-crafting module manually.

**To Reproduce**
Should occur during current workflow of 3.0 NPMified setup.

**Expected behavior**
May want to add the simple-crafting module to the npm run init module script.

**Error logs**
Error: No Entity definition found for craft:greenplant

   at ItemFactory.createByType (/home/ranviermud/ranvier/3.0/Ranvier-Vanaheim-Core/src/EntityFactory.js:66:13)

   at ItemFactory.create (/home/ranviermud/ranvier/3.0/Ranvier-Vanaheim-Core/src/ItemFactory.js:21:23)

   at Room.spawnItem (/home/ranviermud/ranvier/3.0/Ranvier-Vanaheim-Core/src/Room.js:255:39)

   at defaultItems.forEach.defaultItem (/home/ranviermud/ranvier/3.0/Ranvier-Vanaheim-Core/src/Room.js:301:12)

   at Array.forEach (<anonymous>)

   at Room.hydrate (/home/ranviermud/ranvier/3.0/Ranvier-Vanaheim-Core/src/Room.js:296:23)

   at Area.hydrate (/home/ranviermud/ranvier/3.0/Ranvier-Vanaheim-Core/src/Area.js:159:12)

   at BundleManager.loadBundles (/home/ranviermud/ranvier/3.0/Ranvier-Vanaheim-Core/src/BundleManager.js:95:12)

   at init (/home/ranviermud/ranvier/3.0/ranviermud-vanaheim-npm-3.0/ranvier:123:17)

   at Object.<anonymous> (/home/ranviermud/ranvier/3.0/ranviermud-vanaheim-npm-3.0/ranvier:152:1)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Node version: 10.15.0

**Comment by shawncplus** [comment]
Fixed in https://github.com/RanvierMUD/ranviermud/commit/714a086ff93d816996bc84069572d936a5241424
